name: pet_tinder
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bella.jpg
    - lib/assets/fran.jpg
    - lib/assets/johndoe.jpg
    - lib/assets/janesmith.jpg
    - lib/assets/currentuser.jpg